steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Run custom commands
- name: node
  entrypoint: npx
  args: ['webpack']
# Run custom commands
- name: node
  entrypoint: npx
  args: ['serve']
- name: gcr.io/k8s-skaffold/pack
  env:
    - GOOGLE_ENTRYPOINT=npx serve
  args:
    - build
    - 'us.gcr.io/$PROJECT_ID/$REPO_NAME/siwe-frontend:$COMMIT_SHA'
    - '--builder=gcr.io/buildpacks/builder:v1'
    - '--network=cloudbuild'
    - '--path=.'
    - '--env=GOOGLE_ENTRYPOINT'
  id: Buildpack
  entrypoint: pack
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - 'us.gcr.io/$PROJECT_ID/$REPO_NAME/siwe-frontend:$COMMIT_SHA'
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
    - run
    - services
    - update
    - siwe-frontend
    - '--platform=managed'
    - '--image=us.gcr.io/$PROJECT_ID/$REPO_NAME/siwe-frontend:$COMMIT_SHA'
    - >-
      --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
    - '--region=$us-central1'
    - '--quiet'
  id: Deploy
  entrypoint: gcloud
images:
- 'us.gcr.io/$PROJECT_ID/$REPO_NAME/siwe-frontend:$COMMIT_SHA'
# [END cloudbuild_npm_node]
