steps:
# Install dependencies
- name: node
  entrypoint: npm
  args: ['install']
# Run custom commands
- name: node
  entrypoint: npx
  args: ['webpack']
 # Run custom commands
- name: node
  entrypoint: npx
  args: ['serve']
# [END cloudbuild_npm_node]
